using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AgrandarCarta : MonoBehaviour
{
  private Vector3 originalScale; // Tama침o original de la carta
    public float enlargementFactor = 1.1f; // Factor de agrandamiento
  
    private void Start()
    {
        // Guarda el tama침o original de la carta al inicio
        originalScale = transform.localScale;
    }

    private void Update()
    {
        // Verifica si el cursor est치 sobre la carta
        if (RectTransformUtility.RectangleContainsScreenPoint(
            GetComponent<RectTransform>(), Input.mousePosition))
        {
            // Agrandar la carta
            transform.localScale = originalScale * enlargementFactor;
        }
        else
        {
            // Restaurar el tama침o original
            transform.localScale = originalScale;
        }
        
    }
}
